apiVersion: v2
name: monitoring-stack
description: A comprehensive monitoring stack for EKS with Prometheus, Grafana, and Fluent Bit
type: application
version: 0.1.0
appVersion: "1.0"

maintainers:
  - name: DevOps Team
    email: devops@company.com

dependencies:
  - name: kube-prometheus-stack
    version: "54.0.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled

  - name: fluent-bit
    version: "0.21.7"
    repository: https://fluent.github.io/helm-charts
    condition: fluentbit.enabled

keywords:
  - monitoring
  - prometheus
  - grafana
  - fluent-bit
  - observability
  - kubernetes

home: https://github.com/company/eks-monitoring-stack
sources:
  - https://github.com/company/eks-monitoring-stack