# Development environment values for monitoring-stack

global:
  region: us-east-1
  clusterName: eks-monitoring-dev
  environment: dev

# Kube Prometheus Stack overrides for dev
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      # Reduced retention for dev
      retention: 7d
      retentionSize: 20GB

      # Smaller resources for dev
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 4Gi

      # Smaller storage for dev
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi

      # Service account with dev IAM role
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/eks-monitoring-dev-prometheus"

  grafana:
    # Smaller resources for dev
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # Smaller persistence for dev
    persistence:
      size: 5Gi

    # Service account with dev IAM role
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/eks-monitoring-dev-grafana"

  alertmanager:
    alertmanagerSpec:
      # Smaller storage for dev
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi

# Fluent Bit overrides for dev
fluent-bit:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/eks-monitoring-dev-fluent-bit"