# Default values for monitoring-stack
# This is a YAML-formatted file.

# Global configuration
global:
  # AWS region
  region: us-east-1
  # Cluster name
  clusterName: eks-monitoring-cluster
  # Environment (dev, staging, prod)
  environment: dev

# Prometheus configuration
prometheus:
  enabled: true

# Grafana configuration
grafana:
  enabled: true

# Fluent Bit configuration
fluentbit:
  enabled: true

# Kube Prometheus Stack configuration
kube-prometheus-stack:
  # Global settings
  global:
    rbac:
      create: true
      pspEnabled: false

  # Prometheus configuration
  prometheus:
    prometheusSpec:
      # Retention settings
      retention: 15d
      retentionSize: 50GB

      # Resource settings
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 2
          memory: 8Gi

      # Storage configuration
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 100Gi

      # Service account configuration
      serviceAccount:
        create: true
        name: prometheus-server
        annotations:
          eks.amazonaws.com/role-arn: ""  # Will be set per environment

      # Additional scrape configs
      additionalScrapeConfigs: []

  # Grafana configuration
  grafana:
    # Enable Grafana
    enabled: true

    # Admin credentials
    adminPassword: admin123  # Change in production

    # Service account
    serviceAccount:
      create: true
      name: grafana
      annotations:
        eks.amazonaws.com/role-arn: ""  # Will be set per environment

    # Persistence
    persistence:
      enabled: true
      storageClassName: gp3
      size: 10Gi

    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Grafana configuration
    grafana.ini:
      server:
        root_url: http://localhost:3000
      auth:
        disable_login_form: false
      auth.anonymous:
        enabled: false
      security:
        admin_user: admin
        admin_password: admin123

    # Data sources
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-kube-prometheus-prometheus:9090
            access: proxy
            isDefault: true
          - name: CloudWatch
            type: cloudwatch
            jsonData:
              defaultRegion: us-east-1
              authType: default

    # Dashboard providers
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    # Dashboards
    dashboards:
      default:
        kubernetes-cluster-monitoring:
          gnetId: 7249
          revision: 1
          datasource: Prometheus
        kubernetes-pod-monitoring:
          gnetId: 6417
          revision: 1
          datasource: Prometheus

  # AlertManager configuration
  alertmanager:
    alertmanagerSpec:
      # Resources
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

      # Storage
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi

  # Node Exporter configuration
  nodeExporter:
    enabled: true

  # Kube State Metrics configuration
  kubeStateMetrics:
    enabled: true

# Fluent Bit configuration
fluent-bit:
  # Service account
  serviceAccount:
    create: true
    name: fluent-bit
    annotations:
      eks.amazonaws.com/role-arn: ""  # Will be set per environment

  # Resources
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  # Configuration
  config:
    # Service configuration
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ .Values.flush }}
          Log_Level {{ .Values.logLevel }}
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          Health_Check On

    # Input configuration
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 50MB
          Skip_Long_Lines On

      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On

    # Filter configuration
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Kube_URL https://kubernetes.default.svc:443
          Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
          Kube_Tag_Prefix kube.var.log.containers.
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude Off

    # Output configuration
    outputs: |
      [OUTPUT]
          Name cloudwatch_logs
          Match kube.*
          region {{ .Values.global.region }}
          log_group_name /aws/eks/{{ .Values.global.clusterName }}/containers
          log_stream_prefix fluentbit-
          auto_create_group true

      [OUTPUT]
          Name cloudwatch_logs
          Match host.*
          region {{ .Values.global.region }}
          log_group_name /aws/eks/{{ .Values.global.clusterName }}/host
          log_stream_prefix fluentbit-
          auto_create_group true

    # Custom parsers
    customParsers: |
      [PARSER]
          Name docker_no_time
          Format json
          Time_Keep Off
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L